kind: saml
metadata:
  name: authentik
  revision: 7cef3afb-a320-4177-a5c8-b3610c59f935
spec:
  acs: https://teleport.cavj.dev:443/v1/webapi/saml/acs/authentik
  attributes_to_roles:
  - name: http://schemas.xmlsoap.org/claims/Group
    roles:
    - access
    - editor
    - auditor
    - db-access-postgres
    - cavlovicj-ec2-ssh-access
    - argocd-access
    - saml-admin
    - cavlovicj-k8s-access
    value: teleport-admins
  - name: http://schemas.xmlsoap.org/claims/Group
    roles:
    - access
    - editor
    - auditor
    - db-access-postgres
    - cavlovicj-ec2-ssh-access
    - argocd-access
    - saml-admin
    - cavlovicj-k8s-access
    value: teleport-developers
  audience: https://teleport.cavj.dev:443/v1/webapi/saml/acs/authentik
  cert: ""
  display: authentik
  entity_descriptor_url: https://authentik.cavj.dev/application/saml/teleport/metadata/
  issuer: https://authentik.cavj.dev/application/saml/teleport/metadata/
  service_provider_issuer: https://teleport.cavj.dev:443/v1/webapi/saml/acs/authentik
  signing_key_pair:
  sso: https://authentik.cavj.dev/application/saml/teleport/
version: v2

