apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: docker.io/jmutai/kuard-amd64:blue@sha256:4b8b063706ecd9ea3855db6440d727f8c155887627c0da02e1b6f06819a444f7
        imagePullPolicy: IfNotPresent
        name: kuard
        ports:
        - containerPort: 8080
